name: On Pull Request
on: 
  pull_request:
    branches:
      - main
jobs:
  pre-check:
    runs-on: ubuntu-latest
    steps: 
      - name: Run on pull Requset
        run: echo "pull request open main" 
